public enum Codes {
	NULL,
	SUCCESS,
	NO_TASK,
	ERR_OUT_OF_RANGE,
	ERR_INVALID_SIZE,
	ERR_NO_SYMBOLS,
	STATE_IDLE,
	STATE_WORKING,
	STATE_SUCCESS,
	STATE_CANCELLED,
	STATE_FAILED,
	STAGE_LOGICAL_DEDUCTION,
	SUBSTAGE_TWIN_ELIMINATION,
	SUBSTAGE_ONE_POSSIBILITY,
	SUBSTAGE_ONLY_POSSIBILITY,
	STAGE_TRIAL_AND_ERROR
}
