public enum Codes {
	NULL,
	SUCCESS,
	NO_TASK,
	ERR_OUT_OF_RANGE,
	ERR_INVALID_SIZE,
	ERR_NO_SYMBOLS,
	STATE_IDLE,
	STATE_CONFLICT,
	STATE_WORKING,
	STATE_SUCCESS,
	STATE_CANCELLED,
	STATE_FAILED,
	STAGE_LOGICAL_DEDUCTION,
	STAGE_TRIAL_AND_ERROR
}
